### ISSUE TITLE
New Version store with global state

### ISSUE THREAD

**Issue by rymurr** [projectnessie/nessie#1977]
Remaining tasks:

- [X] database-adapters / base interface + common logic implementation
- [X] database-adapters / tests
- [X] database-adapters / non-transactional base
- [X] database-adapters / in-memory
- [x] database-adapters / rocksdb
- [x] database-adapters / mongodb (#1943)
- [x] database-adapters / transactional base
- [x] database-adapters / transactional implementations for H2 + Postgres/Cockroach
- [x] global-states API change (#1922) 
- [x] global-states API implementation (#1923)
- [x] JUnit extension to inject `DatabaseAdapter` + `VersionStore` into static fields, instance fields, method parameters (#2010)
- [x] Add new version-store implementation incl tests (#2083)
- [x] Quarkus prod code/config changes (#2085)
- [x] Add new Quarkus integration tests exercising all supported backend stores (#2085)
- [x] Update markdown/readme files (#2086)
- [ ] New Nessie-GC implementation
- [ ] Iceberg integration
- [x] Cleanup: remove old version-store implementations, remove "backwards compatibility code", etc (#2112)
- [ ] Add Spark-SQL-extensions for Nessie-GC (#1511)

**Comment by snazy** [comment]
Moved remaining tasks into #2254 + #2255 - closing this one
