### ISSUE TITLE
Add release branches

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4597]
Using a workflow like this:
1. Create a new branch in projectnessie/nessie following the name pattern `release-*`, where `*` represents the major+minor version
2. Optionally cherry-pick additional commits from `main` branch onto the `release-*` branch
3. Call `Create Release` workflow with intended version number + the `release-x.y` branch name

- [x] Add branch protection rule for `relase-*`
- [x] #4593 Simplify steps outputs handling (for #4596)
- [x] #4594 Add workflow to manually bump the development version on the main branch
- [x] #4595 Run main CI workflow also on `release-*` branches
- [x] #4596 Update release-publish workflow to checkout from another branch + work with both Gradle + Maven
