### ISSUE TITLE
Remove old baggage for Nessie 1.0 GA

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#4847]
Ticket is an umbrella for a few things:

- [x] Remove code to support global state et al (requires export/import)
- [x] Fix split-packages #5070
- [x] Remove "legacy" handling of payload==0 #4956
- [x] Entirely remove code that handles global state #4957
- [x] Idea: revisit Maven group IDs for published Nessie artifacts #5019
- [ ] Rename jax-rs-* projects #5119
