### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#5112]
Umbrella ticket for all API v2 tickets & PRs

* [ ] WIP PR #5004 
* [ ] Add generic java client runtime exceptions #4599
* [ ] Support retrying idempotent operations in the HttpClient (java) #4598
* [ ] Support cachable REST responses #5111

**Comment by dimas-b** [comment]
Moved some sub-tasks to #5645
