### ISSUE TITLE
Spark SQL Extensions for Nessie 1.0 GA

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie#5113]
Umbrella ticket for Spark SQL extension related tickets:

* [ ] SQL Extension `SHOW LOG` with `AT` #4665 
* [ ] SQL Extension `CREATE (BRANCH|TAG)` with `AT` #4666
* [ ] SQL Extension MERGE BRANCH #4667 #4667
* [ ] Cherry-pick or transplant is not supported from SQL extension #2269

**Comment by ajantha-bhat** [comment]
I have added https://github.com/projectnessie/nessie/issues/2269

**Comment by snazy** [comment]
Closing, as most of the issued are already resolved
