### ISSUE TITLE
API v2 Follow-up

### ISSUE THREAD

**Issue by dimas-b** [projectnessie/nessie#5645]
Follow-up work for #5112 

* [x] Update Iceberg: https://github.com/apache/iceberg/issues/6031
* [x] Conflict resolution parameters for commits.
* [x] Review and update commit information (e.g. message) created for merge + transplant operations #4430
* [x] Additional commit parents #5634
* [x] V2 is SQL tests #5663
* [ ] Add generic java client runtime exceptions #4599
* [x] Refactor `NessieError` and `ErrorCode` to become extensible #4310
* [ ] Use API v2 in UI #5410 
* [x] Paginated `getEnties` #5448 
* [ ] Support retrying idempotent operations in the HttpClient (java) #4598
* [ ] Support cachable REST responses #5111
* [ ] Evaluate usage of RevAPI #4133 (this is related, but might help to prove compatibility)
* [x] Handle relative hashes in Reference #1352 
* [x] ContentKey based filter in the Nessie Diff API #3957
* [x] Pre-GA API "think-through" #1804

**Comment by snazy** [comment]
Closing this umbrella issue, but leave the individual issues open, if applicable
